export interface CurrencyEntry {
  code: string
  symbol: string
}

// NOK, EUR, USD, GBP are pinned at the top; rest sorted alphabetically
const PINNED_CODES = ['NOK', 'EUR', 'USD', 'GBP']

// Full ISO 4217 list — base source: CurrencyWidget.tsx (162 entries)
const ALL_ENTRIES: CurrencyEntry[] = [
  { code: 'AED', symbol: 'د.إ' },
  { code: 'AFN', symbol: '؋' },
  { code: 'ALL', symbol: 'L' },
  { code: 'AMD', symbol: '֏' },
  { code: 'ANG', symbol: 'ƒ' },
  { code: 'AOA', symbol: 'Kz' },
  { code: 'ARS', symbol: 'AR$' },
  { code: 'AUD', symbol: 'A$' },
  { code: 'AWG', symbol: 'ƒ' },
  { code: 'AZN', symbol: '₼' },
  { code: 'BAM', symbol: 'KM' },
  { code: 'BBD', symbol: 'BB$' },
  { code: 'BDT', symbol: '৳' },
  { code: 'BGN', symbol: 'лв' },
  { code: 'BHD', symbol: 'BD' },
  { code: 'BIF', symbol: 'Fr' },
  { code: 'BMD', symbol: '$' },
  { code: 'BND', symbol: '$' },
  { code: 'BOB', symbol: 'Bs' },
  { code: 'BRL', symbol: 'R$' },
  { code: 'BSD', symbol: '$' },
  { code: 'BTN', symbol: 'Nu' },
  { code: 'BWP', symbol: 'P' },
  { code: 'BYN', symbol: 'Br' },
  { code: 'BZD', symbol: 'BZ$' },
  { code: 'CAD', symbol: 'C$' },
  { code: 'CDF', symbol: 'Fr' },
  { code: 'CHF', symbol: 'CHF' },
  { code: 'CLF', symbol: 'UF' },
  { code: 'CLP', symbol: 'CL$' },
  { code: 'CNH', symbol: '¥' },
  { code: 'CNY', symbol: '¥' },
  { code: 'COP', symbol: 'CO$' },
  { code: 'CRC', symbol: '₡' },
  { code: 'CUP', symbol: '$' },
  { code: 'CVE', symbol: '$' },
  { code: 'CZK', symbol: 'Kč' },
  { code: 'DJF', symbol: 'Fr' },
  { code: 'DKK', symbol: 'kr' },
  { code: 'DOP', symbol: 'RD$' },
  { code: 'DZD', symbol: 'دج' },
  { code: 'EGP', symbol: 'E£' },
  { code: 'ERN', symbol: 'Nfk' },
  { code: 'ETB', symbol: 'Br' },
  { code: 'EUR', symbol: '€' },
  { code: 'FJD', symbol: 'FJ$' },
  { code: 'FKP', symbol: '£' },
  { code: 'FOK', symbol: 'kr' },
  { code: 'GBP', symbol: '£' },
  { code: 'GEL', symbol: '₾' },
  { code: 'GGP', symbol: '£' },
  { code: 'GHS', symbol: '₵' },
  { code: 'GIP', symbol: '£' },
  { code: 'GMD', symbol: 'D' },
  { code: 'GNF', symbol: 'Fr' },
  { code: 'GTQ', symbol: 'Q' },
  { code: 'GYD', symbol: '$' },
  { code: 'HKD', symbol: 'HK$' },
  { code: 'HNL', symbol: 'L' },
  { code: 'HRK', symbol: 'kn' },
  { code: 'HTG', symbol: 'G' },
  { code: 'HUF', symbol: 'Ft' },
  { code: 'IDR', symbol: 'Rp' },
  { code: 'ILS', symbol: '₪' },
  { code: 'IMP', symbol: '£' },
  { code: 'INR', symbol: '₹' },
  { code: 'IQD', symbol: 'ع.د' },
  { code: 'ISK', symbol: 'kr' },
  { code: 'JEP', symbol: '£' },
  { code: 'JMD', symbol: 'J$' },
  { code: 'JOD', symbol: 'JD' },
  { code: 'JPY', symbol: '¥' },
  { code: 'KES', symbol: 'KSh' },
  { code: 'KGS', symbol: 'лв' },
  { code: 'KHR', symbol: '៛' },
  { code: 'KID', symbol: '$' },
  { code: 'KMF', symbol: 'Fr' },
  { code: 'KRW', symbol: '₩' },
  { code: 'KWD', symbol: 'KD' },
  { code: 'KYD', symbol: '$' },
  { code: 'KZT', symbol: '₸' },
  { code: 'LAK', symbol: '₭' },
  { code: 'LBP', symbol: '£' },
  { code: 'LKR', symbol: 'Rs' },
  { code: 'LRD', symbol: '$' },
  { code: 'LSL', symbol: 'L' },
  { code: 'LYD', symbol: 'LD' },
  { code: 'MAD', symbol: 'MAD' },
  { code: 'MDL', symbol: 'L' },
  { code: 'MGA', symbol: 'Ar' },
  { code: 'MKD', symbol: 'ден' },
  { code: 'MMK', symbol: 'K' },
  { code: 'MNT', symbol: '₮' },
  { code: 'MOP', symbol: 'P' },
  { code: 'MRU', symbol: 'UM' },
  { code: 'MUR', symbol: 'Rs' },
  { code: 'MVR', symbol: 'Rf' },
  { code: 'MWK', symbol: 'MK' },
  { code: 'MXN', symbol: 'MX$' },
  { code: 'MYR', symbol: 'RM' },
  { code: 'MZN', symbol: 'MT' },
  { code: 'NAD', symbol: '$' },
  { code: 'NGN', symbol: '₦' },
  { code: 'NIO', symbol: 'C$' },
  { code: 'NOK', symbol: 'kr' },
  { code: 'NPR', symbol: 'Rs' },
  { code: 'NZD', symbol: 'NZ$' },
  { code: 'OMR', symbol: 'ر.ع.' },
  { code: 'PAB', symbol: 'B/.' },
  { code: 'PEN', symbol: 'S/.' },
  { code: 'PGK', symbol: 'K' },
  { code: 'PHP', symbol: '₱' },
  { code: 'PKR', symbol: '₨' },
  { code: 'PLN', symbol: 'zł' },
  { code: 'PYG', symbol: '₲' },
  { code: 'QAR', symbol: 'ر.ق' },
  { code: 'RON', symbol: 'lei' },
  { code: 'RSD', symbol: 'din.' },
  { code: 'RUB', symbol: '₽' },
  { code: 'RWF', symbol: 'Fr' },
  { code: 'SAR', symbol: '﷼' },
  { code: 'SBD', symbol: '$' },
  { code: 'SCR', symbol: '₨' },
  { code: 'SDG', symbol: 'ج.س.' },
  { code: 'SEK', symbol: 'kr' },
  { code: 'SGD', symbol: 'S$' },
  { code: 'SHP', symbol: '£' },
  { code: 'SLE', symbol: 'Le' },
  { code: 'SOS', symbol: 'Sh' },
  { code: 'SRD', symbol: '$' },
  { code: 'SSP', symbol: '£' },
  { code: 'STN', symbol: 'Db' },
  { code: 'SYP', symbol: '£' },
  { code: 'SZL', symbol: 'L' },
  { code: 'THB', symbol: '฿' },
  { code: 'TJS', symbol: 'SM' },
  { code: 'TMT', symbol: 'T' },
  { code: 'TND', symbol: 'DT' },
  { code: 'TOP', symbol: 'T$' },
  { code: 'TRY', symbol: '₺' },
  { code: 'TTD', symbol: 'TT$' },
  { code: 'TVD', symbol: '$' },
  { code: 'TWD', symbol: 'NT$' },
  { code: 'TZS', symbol: 'Sh' },
  { code: 'UAH', symbol: '₴' },
  { code: 'UGX', symbol: 'Sh' },
  { code: 'USD', symbol: '$' },
  { code: 'UYU', symbol: '$U' },
  { code: 'UZS', symbol: 'лв' },
  { code: 'VES', symbol: 'Bs.S' },
  { code: 'VND', symbol: '₫' },
  { code: 'VUV', symbol: 'Vt' },
  { code: 'WST', symbol: 'WS$' },
  { code: 'XAF', symbol: 'Fr' },
  { code: 'XCD', symbol: '$' },
  { code: 'XDR', symbol: 'SDR' },
  { code: 'XOF', symbol: 'Fr' },
  { code: 'XPF', symbol: 'Fr' },
  { code: 'YER', symbol: 'ر.ي' },
  { code: 'ZAR', symbol: 'R' },
  { code: 'ZMW', symbol: 'ZK' },
  { code: 'ZWL', symbol: '$' },
]

const pinnedEntries = PINNED_CODES.map(code => ALL_ENTRIES.find(e => e.code === code)!)
const restEntries = ALL_ENTRIES
  .filter(e => !PINNED_CODES.includes(e.code))
  .sort((a, b) => a.code.localeCompare(b.code))

export const CURRENCIES: CurrencyEntry[] = [...pinnedEntries, ...restEntries]

export const CURRENCY_CODES: string[] = CURRENCIES.map(e => e.code)

export const CURRENCY_SYMBOLS: Record<string, string> = Object.fromEntries(
  CURRENCIES.map(e => [e.code, e.symbol])
)
